// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvtekmeclzesuoezdase.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2dGVrbWVjbHplc3VvZXpkYXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzk3NTYsImV4cCI6MjA1ODgxNTc1Nn0.RfyXzhJjwjL_U9bUffKyHCFEm4bfos5luieoZIevRb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);